### ISSUE TITLE
odule [groovy-jsr223 is loaded in version 3.0.9 and you are trying to load version 3.0.13

### ISSUE THREAD

**Issue by YannickRobin** [YannickRobin/easy-gradle-plugin#5]
I have the following error when I execute `gradle test` on my extension using the plugin:
`        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 3.0.9 and you are trying to load version 3.0.13`

**Comment by YannickRobin** [comment]
`gradle -q dependencies` shows that 3.0.13 is defined in my project

`testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.codehaus.groovy:groovy-all:3.0.13
|    +--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-ant:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    +--- org.apache.ant:ant:1.10.12
|    |    |    \--- org.apache.ant:ant-launcher:1.10.12
|    |    +--- org.apache.ant:ant-junit:1.10.12
|    |    |    \--- org.apache.ant:ant:1.10.12 (*)
|    |    +--- org.apache.ant:ant-launcher:1.10.12
|    |    +--- org.apache.ant:ant-antlr:1.10.12
|    |    \--- org.codehaus.groovy:groovy-groovydoc:3.0.13
|    |         +--- org.codehaus.groovy:groovy:3.0.13
|    |         +--- com.github.javaparser:javaparser-core:3.24.2
|    |         +--- org.codehaus.groovy:groovy-templates:3.0.13
|    |         |    +--- org.codehaus.groovy:groovy:3.0.13
|    |         |    \--- org.codehaus.groovy:groovy-xml:3.0.13
|    |         |         \--- org.codehaus.groovy:groovy:3.0.13
|    |         \--- org.codehaus.groovy:groovy-docgenerator:3.0.13
|    |              +--- org.codehaus.groovy:groovy-templates:3.0.13 (*)
|    |              +--- org.codehaus.groovy:groovy:3.0.13
|    |              \--- com.thoughtworks.qdox:qdox:1.12.1
|    +--- org.codehaus.groovy:groovy-astbuilder:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-cli-picocli:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    \--- info.picocli:picocli:4.6.3
|    +--- org.codehaus.groovy:groovy-console:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    +--- org.codehaus.groovy:groovy-templates:3.0.13 (*)
|    |    \--- org.codehaus.groovy:groovy-swing:3.0.13
|    |         \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-datetime:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-docgenerator:3.0.13 (*)
|    +--- org.codehaus.groovy:groovy-groovydoc:3.0.13 (*)
|    +--- org.codehaus.groovy:groovy-groovysh:3.0.13
|    |    +--- org.codehaus.groovy:groovy-templates:3.0.13 (*)
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    +--- org.codehaus.groovy:groovy-console:3.0.13 (*)
|    |    +--- org.codehaus.groovy:groovy-xml:3.0.13 (*)
|    |    \--- jline:jline:2.14.6
|    +--- org.codehaus.groovy:groovy-jmx:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-json:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-jsr223:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-macro:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-nio:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-servlet:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    +--- org.codehaus.groovy:groovy-templates:3.0.13 (*)
|    |    \--- org.codehaus.groovy:groovy-xml:3.0.13 (*)
|    +--- org.codehaus.groovy:groovy-sql:3.0.13
|    |    \--- org.codehaus.groovy:groovy:3.0.13
|    +--- org.codehaus.groovy:groovy-swing:3.0.13 (*)
|    +--- org.codehaus.groovy:groovy-templates:3.0.13 (*)
|    +--- org.codehaus.groovy:groovy-test:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    \--- junit:junit:4.13.2
|    |         \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.codehaus.groovy:groovy-test-junit5:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    +--- org.junit.jupiter:junit-jupiter-api:5.8.2 -> 5.10.1
|    |    |    +--- org.junit:junit-bom:5.10.1
|    |    |    |    +--- org.junit.jupiter:junit-jupiter-api:5.10.1 (c)
|    |    |    |    +--- org.junit.jupiter:junit-jupiter-engine:5.10.1 (c)
|    |    |    |    +--- org.junit.platform:junit-platform-engine:1.10.1 (c)
|    |    |    |    +--- org.junit.platform:junit-platform-launcher:1.10.1 (c)
|    |    |    |    +--- org.junit.vintage:junit-vintage-engine:5.10.1 (c)
|    |    |    |    \--- org.junit.platform:junit-platform-commons:1.10.1 (c)
|    |    |    +--- org.opentest4j:opentest4j:1.3.0
|    |    |    \--- org.junit.platform:junit-platform-commons:1.10.1
|    |    |         \--- org.junit:junit-bom:5.10.1 (*)
|    |    +--- org.junit.platform:junit-platform-launcher:1.8.2 -> 1.10.1
|    |    |    +--- org.junit:junit-bom:5.10.1 (*)
|    |    |    \--- org.junit.platform:junit-platform-engine:1.10.1
|    |    |         +--- org.junit:junit-bom:5.10.1 (*)
|    |    |         +--- org.opentest4j:opentest4j:1.3.0
|    |    |         \--- org.junit.platform:junit-platform-commons:1.10.1 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-engine:5.8.2 -> 5.10.1
|    |         +--- org.junit:junit-bom:5.10.1 (*)
|    |         +--- org.junit.platform:junit-platform-engine:1.10.1 (*)
|    |         \--- org.junit.jupiter:junit-jupiter-api:5.10.1 (*)
|    +--- org.codehaus.groovy:groovy-testng:3.0.13
|    |    +--- org.codehaus.groovy:groovy:3.0.13
|    |    \--- org.testng:testng:7.5
|    |         +--- org.slf4j:slf4j-api:1.7.32
|    |         +--- com.beust:jcommander:1.78
|    |         \--- org.webjars:jquery:3.5.1
|    \--- org.codehaus.groovy:groovy-xml:3.0.13 (*)
\--- org.junit.vintage:junit-vintage-engine:5.10.1
     +--- org.junit:junit-bom:5.10.1 (*)
     +--- org.junit.platform:junit-platform-engine:1.10.1 (*)
     \--- junit:junit:4.13.2 (*)`

We can confirm 3.0.13 is defined in the EasyPlugin class of the plugin 
`project.dependencies.add('implementation', 'org.codehaus.groovy:groovy-all:3.0.13')`

There is a conflict with Groovy version in my platform.

**Comment by YannickRobin** [comment]
@apanwar In the last version of the plugin, it works on my machine if I remove the dependency to Groovy.
Can you check if this is necessary for you?
```
        project.dependencies.add('implementation', 'org.codehaus.groovy:groovy-all:3.0.13')
```
