### ISSUE TITLE
"No name attribute provided for Appender db" error when executing Spock integration test

### ISSUE THREAD

**Issue by YannickRobin** [YannickRobin/easy-gradle-plugin#9]
I have the following exception when I execute Spock integration test

```
java.lang.ExceptionInInitializerError
	at org.apache.http.conn.ssl.SSLSocketFactory.<clinit>(SSLSocketFactory.java:154)
	at io.restassured.config.SSLConfig.<init>(SSLConfig.java:184)
	at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:421)
	at io.restassured.builder.RequestSpecBuilder.<init>(RequestSpecBuilder.java:79)
	at com.sap.cx.boosters.easy.extension.helloworld.easyrest.controller.HelloWorldControllerSpockIntegrationTest.test easy hello world(HelloWorldControllerSpockIntegrationTest.groovy:16)
Caused by: org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Appender db
	at app//org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createAppender(PropertiesConfigurationBuilder.java:219)
	at app//org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:152)
	at app//org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:56)
	at app//de.hybris.platform.util.logging.log4j2.HybrisLog4j2ConfigurationFactory.loadConfigFromProperties(HybrisLog4j2ConfigurationFactory.java:80)
	at app//de.hybris.platform.util.logging.log4j2.HybrisLog4j2ConfigurationFactory.getConfiguration(HybrisLog4j2ConfigurationFactory.java:57)
	at app//org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:437)
	at app//org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:325)
	at app//org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
	at app//org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at app//org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at app//org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at app//org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at app//org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at app//org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at app//org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
	at app//org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at app//org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at app//org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at app//org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at app//org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at app//org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at app//org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at app//org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	... 6 more
```

**Comment by YannickRobin** [comment]
We see `HybrisLog4j2ConfigurationFactory.loadConfigFromProperties` is used.

In my local, I had references to log4j2 appenders.
```
log4j2.appender.db.columnConfigs[0].isEventTimestamp=true
log4j2.appender.db.columnConfigs[0].pattern=
log4j2.logger.de.hybris.platform.audit.actions.impl.Slf4jAuditableActionHandler.level = ERROR
```

Removing these references solved my issue.
